// Copyright 2026 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build integration

// Code generated by cmd/generate-tests. DO NOT EDIT.

package test

var generatedTests = []*testCase{
	{
		// Covers: OutputEncoding.CustomBitrate, OutputType.File, PublisherCodec.PublishH264, RequestType.Media
		name: "CustomBitrate/File/Media/PublishH264",
		options: []Mutation{
			OutputEncodings.CustomBitrate.Apply,
			OutputTypes.File.Apply,
			PublisherCodecs.PublishH264.Apply,
			RequestTypes.Media.Apply,
		},
	},
	{
		// Covers: OutputEncoding.EncodingAAC, OutputType.FileAndSegments, PublisherCodec.PublishOpus, RequestType.MediaAudioOnly
		name: "EncodingAAC/FileAndSegments/MediaAudioOnly/PublishOpus",
		options: []Mutation{
			OutputEncodings.EncodingAAC.Apply,
			OutputTypes.FileAndSegments.Apply,
			PublisherCodecs.PublishOpus.Apply,
			RequestTypes.MediaAudioOnly.Apply,
		},
	},
	{
		// Covers: OutputEncoding.EncodingH264Baseline, OutputType.FileAndImages, PublisherCodec.PublishVP8, RequestType.MediaAudioRouteByIdentity
		name: "EncodingH264Baseline/FileAndImages/MediaAudioRouteByIdentity/PublishVP8",
		options: []Mutation{
			OutputEncodings.EncodingH264Baseline.Apply,
			OutputTypes.FileAndImages.Apply,
			PublisherCodecs.PublishVP8.Apply,
			RequestTypes.MediaAudioRouteByIdentity.Apply,
		},
	},
	{
		// Covers: OutputEncoding.EncodingOpus, OutputType.FileAndStream, PublisherCodec.PublishPCMA, RequestType.MediaAudioRouteByKind
		name: "EncodingOpus/FileAndStream/MediaAudioRouteByKind/PublishPCMA",
		options: []Mutation{
			OutputEncodings.EncodingOpus.Apply,
			OutputTypes.FileAndStream.Apply,
			PublisherCodecs.PublishPCMA.Apply,
			RequestTypes.MediaAudioRouteByKind.Apply,
		},
	},
	{
		// Covers: OutputEncoding.FileMP3, OutputType.Segments, PublisherCodec.PublishPCMU, RequestType.MediaAudioRouteByTrackID
		name: "FileMP3/MediaAudioRouteByTrackID/PublishPCMU/Segments",
		options: []Mutation{
			OutputEncodings.FileMP3.Apply,
			OutputTypes.Segments.Apply,
			PublisherCodecs.PublishPCMU.Apply,
			RequestTypes.MediaAudioRouteByTrackID.Apply,
		},
	},
	{
		// Covers: OutputEncoding.EncodingH264High, OutputType.Images, RequestType.MediaMultiRoute
		name: "EncodingH264High/Images/MediaMultiRoute",
		options: []Mutation{
			OutputEncodings.EncodingH264High.Apply,
			OutputTypes.Images.Apply,
			RequestTypes.MediaMultiRoute.Apply,
		},
	},
	{
		// Covers: OutputEncoding.EncodingH264Main, OutputType.SegmentsAndImages, RequestType.MediaParticipantVideo
		name: "EncodingH264Main/MediaParticipantVideo/SegmentsAndImages",
		options: []Mutation{
			OutputEncodings.EncodingH264Main.Apply,
			OutputTypes.SegmentsAndImages.Apply,
			RequestTypes.MediaParticipantVideo.Apply,
		},
	},
	{
		// Covers: OutputEncoding.FileMP4, OutputType.Stream, RequestType.MediaVideoOnly
		name: "FileMP4/MediaVideoOnly/Stream",
		options: []Mutation{
			OutputEncodings.FileMP4.Apply,
			OutputTypes.Stream.Apply,
			RequestTypes.MediaVideoOnly.Apply,
		},
	},
	{
		// Covers: OutputEncoding.FileOGG, OutputType.StreamAndSegments, RequestType.Participant
		name: "FileOGG/Participant/StreamAndSegments",
		options: []Mutation{
			OutputEncodings.FileOGG.Apply,
			OutputTypes.StreamAndSegments.Apply,
			RequestTypes.Participant.Apply,
		},
	},
	{
		// Covers: OutputEncoding.FileTS, OutputType.StreamAndImages, RequestType.RoomComposite
		name: "FileTS/RoomComposite/StreamAndImages",
		options: []Mutation{
			OutputEncodings.FileTS.Apply,
			OutputTypes.StreamAndImages.Apply,
			RequestTypes.RoomComposite.Apply,
		},
	},
	{
		// Covers: OutputEncoding.FileIVF, RequestType.TrackVideo
		name: "FileIVF/TrackVideo",
		options: []Mutation{
			OutputEncodings.FileIVF.Apply,
			RequestTypes.TrackVideo.Apply,
		},
	},
	{
		// Covers: OutputEncoding.FileWebM, RequestType.RoomCompositeVideoOnly
		name: "FileWebM/RoomCompositeVideoOnly",
		options: []Mutation{
			OutputEncodings.FileWebM.Apply,
			RequestTypes.RoomCompositeVideoOnly.Apply,
		},
	},
	{
		// Covers: OutputEncoding.ImageSuffixIndex, RequestType.TemplateGrid
		name: "ImageSuffixIndex/TemplateGrid",
		options: []Mutation{
			OutputEncodings.ImageSuffixIndex.Apply,
			RequestTypes.TemplateGrid.Apply,
		},
	},
	{
		// Covers: OutputEncoding.ImageSuffixTimestamp, RequestType.TemplateSingleSpeaker
		name: "ImageSuffixTimestamp/TemplateSingleSpeaker",
		options: []Mutation{
			OutputEncodings.ImageSuffixTimestamp.Apply,
			RequestTypes.TemplateSingleSpeaker.Apply,
		},
	},
	{
		// Covers: OutputEncoding.KeyFrameInterval2s, RequestType.TemplateSpeaker
		name: "KeyFrameInterval2s/TemplateSpeaker",
		options: []Mutation{
			OutputEncodings.KeyFrameInterval2s.Apply,
			RequestTypes.TemplateSpeaker.Apply,
		},
	},
	{
		// Covers: OutputEncoding.Resolution1080p, RequestType.TrackComposite
		name: "Resolution1080p/TrackComposite",
		options: []Mutation{
			OutputEncodings.Resolution1080p.Apply,
			RequestTypes.TrackComposite.Apply,
		},
	},
	{
		// Covers: OutputEncoding.Resolution360p, RequestType.TrackCompositeVideoOnly
		name: "Resolution360p/TrackCompositeVideoOnly",
		options: []Mutation{
			OutputEncodings.Resolution360p.Apply,
			RequestTypes.TrackCompositeVideoOnly.Apply,
		},
	},
	{
		// Covers: OutputEncoding.Resolution720p, RequestType.Web
		name: "Resolution720p/Web",
		options: []Mutation{
			OutputEncodings.Resolution720p.Apply,
			RequestTypes.Web.Apply,
		},
	},
	{
		// Covers: OutputEncoding.SegmentLivePlaylist, RequestType.ParticipantAudioOnly
		name: "ParticipantAudioOnly/SegmentLivePlaylist",
		options: []Mutation{
			OutputEncodings.SegmentLivePlaylist.Apply,
			RequestTypes.ParticipantAudioOnly.Apply,
		},
	},
	{
		// Covers: OutputEncoding.SegmentSuffixIndex, RequestType.RoomCompositeAudioOnly
		name: "RoomCompositeAudioOnly/SegmentSuffixIndex",
		options: []Mutation{
			OutputEncodings.SegmentSuffixIndex.Apply,
			RequestTypes.RoomCompositeAudioOnly.Apply,
		},
	},
	{
		// Covers: OutputEncoding.SegmentSuffixTimestamp, RequestType.TrackCompositeAudioOnly
		name: "SegmentSuffixTimestamp/TrackCompositeAudioOnly",
		options: []Mutation{
			OutputEncodings.SegmentSuffixTimestamp.Apply,
			RequestTypes.TrackCompositeAudioOnly.Apply,
		},
	},
	{
		// Covers: OutputEncoding.StreamRTMP, RequestType.WebV2
		name: "StreamRTMP/WebV2",
		options: []Mutation{
			OutputEncodings.StreamRTMP.Apply,
			RequestTypes.WebV2.Apply,
		},
	},
	{
		// Covers: OutputEncoding.StreamSRT, RequestType.WebV2AudioOnly
		name: "StreamSRT/WebV2AudioOnly",
		options: []Mutation{
			OutputEncodings.StreamSRT.Apply,
			RequestTypes.WebV2AudioOnly.Apply,
		},
	},
	{
		// Covers: OutputEncoding.StreamWebsocket, RequestType.TrackAudio
		name: "StreamWebsocket/TrackAudio",
		options: []Mutation{
			OutputEncodings.StreamWebsocket.Apply,
			RequestTypes.TrackAudio.Apply,
		},
	},
	{
		// Covers: RequestType.WebV2VideoOnly
		name: "WebV2VideoOnly",
		options: []Mutation{
			RequestTypes.WebV2VideoOnly.Apply,
		},
	},
}
