// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: ipc.proto

package ipc

import (
	livekit "github.com/livekit/protocol/livekit"
	rpc "github.com/livekit/protocol/rpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandlerReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EgressId      string                 `protobuf:"bytes,1,opt,name=egress_id,json=egressId,proto3" json:"egress_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerReadyRequest) Reset() {
	*x = HandlerReadyRequest{}
	mi := &file_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerReadyRequest) ProtoMessage() {}

func (x *HandlerReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerReadyRequest.ProtoReflect.Descriptor instead.
func (*HandlerReadyRequest) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *HandlerReadyRequest) GetEgressId() string {
	if x != nil {
		return x.EgressId
	}
	return ""
}

type HandlerFinishedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EgressId      string                 `protobuf:"bytes,1,opt,name=egress_id,json=egressId,proto3" json:"egress_id,omitempty"`
	Metrics       string                 `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Info          *livekit.EgressInfo    `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerFinishedRequest) Reset() {
	*x = HandlerFinishedRequest{}
	mi := &file_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerFinishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerFinishedRequest) ProtoMessage() {}

func (x *HandlerFinishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerFinishedRequest.ProtoReflect.Descriptor instead.
func (*HandlerFinishedRequest) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *HandlerFinishedRequest) GetEgressId() string {
	if x != nil {
		return x.EgressId
	}
	return ""
}

func (x *HandlerFinishedRequest) GetMetrics() string {
	if x != nil {
		return x.Metrics
	}
	return ""
}

func (x *HandlerFinishedRequest) GetInfo() *livekit.EgressInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type StorageEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EgressId      string                 `protobuf:"bytes,1,opt,name=egress_id,json=egressId,proto3" json:"egress_id,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	LifetimeDays  int64                  `protobuf:"varint,5,opt,name=lifetime_days,json=lifetimeDays,proto3" json:"lifetime_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageEventRequest) Reset() {
	*x = StorageEventRequest{}
	mi := &file_ipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageEventRequest) ProtoMessage() {}

func (x *StorageEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageEventRequest.ProtoReflect.Descriptor instead.
func (*StorageEventRequest) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{2}
}

func (x *StorageEventRequest) GetEgressId() string {
	if x != nil {
		return x.EgressId
	}
	return ""
}

func (x *StorageEventRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *StorageEventRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StorageEventRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StorageEventRequest) GetLifetimeDays() int64 {
	if x != nil {
		return x.LifetimeDays
	}
	return 0
}

type GstPipelineDebugDotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GstPipelineDebugDotRequest) Reset() {
	*x = GstPipelineDebugDotRequest{}
	mi := &file_ipc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GstPipelineDebugDotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GstPipelineDebugDotRequest) ProtoMessage() {}

func (x *GstPipelineDebugDotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GstPipelineDebugDotRequest.ProtoReflect.Descriptor instead.
func (*GstPipelineDebugDotRequest) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{3}
}

type GstPipelineDebugDotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DotFile       string                 `protobuf:"bytes,1,opt,name=dot_file,json=dotFile,proto3" json:"dot_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GstPipelineDebugDotResponse) Reset() {
	*x = GstPipelineDebugDotResponse{}
	mi := &file_ipc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GstPipelineDebugDotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GstPipelineDebugDotResponse) ProtoMessage() {}

func (x *GstPipelineDebugDotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GstPipelineDebugDotResponse.ProtoReflect.Descriptor instead.
func (*GstPipelineDebugDotResponse) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{4}
}

func (x *GstPipelineDebugDotResponse) GetDotFile() string {
	if x != nil {
		return x.DotFile
	}
	return ""
}

type PProfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileName   string                 `protobuf:"bytes,1,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Debug         int32                  `protobuf:"varint,3,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PProfRequest) Reset() {
	*x = PProfRequest{}
	mi := &file_ipc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PProfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PProfRequest) ProtoMessage() {}

func (x *PProfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PProfRequest.ProtoReflect.Descriptor instead.
func (*PProfRequest) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{5}
}

func (x *PProfRequest) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *PProfRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *PProfRequest) GetDebug() int32 {
	if x != nil {
		return x.Debug
	}
	return 0
}

type PProfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PprofFile     []byte                 `protobuf:"bytes,1,opt,name=pprof_file,json=pprofFile,proto3" json:"pprof_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PProfResponse) Reset() {
	*x = PProfResponse{}
	mi := &file_ipc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PProfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PProfResponse) ProtoMessage() {}

func (x *PProfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PProfResponse.ProtoReflect.Descriptor instead.
func (*PProfResponse) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{6}
}

func (x *PProfResponse) GetPprofFile() []byte {
	if x != nil {
		return x.PprofFile
	}
	return nil
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_ipc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{7}
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       string                 `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_ipc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{8}
}

func (x *MetricsResponse) GetMetrics() string {
	if x != nil {
		return x.Metrics
	}
	return ""
}

type KillEgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillEgressRequest) Reset() {
	*x = KillEgressRequest{}
	mi := &file_ipc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillEgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillEgressRequest) ProtoMessage() {}

func (x *KillEgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillEgressRequest.ProtoReflect.Descriptor instead.
func (*KillEgressRequest) Descriptor() ([]byte, []int) {
	return file_ipc_proto_rawDescGZIP(), []int{9}
}

func (x *KillEgressRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_ipc_proto protoreflect.FileDescriptor

const file_ipc_proto_rawDesc = "" +
	"\n" +
	"\tipc.proto\x12\x03ipc\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14livekit_egress.proto\x1a\x10rpc/egress.proto\"2\n" +
	"\x13HandlerReadyRequest\x12\x1b\n" +
	"\tegress_id\x18\x01 \x01(\tR\begressId\"x\n" +
	"\x16HandlerFinishedRequest\x12\x1b\n" +
	"\tegress_id\x18\x01 \x01(\tR\begressId\x12\x18\n" +
	"\ametrics\x18\x02 \x01(\tR\ametrics\x12'\n" +
	"\x04info\x18\x03 \x01(\v2\x13.livekit.EgressInfoR\x04info\"\x9d\x01\n" +
	"\x13StorageEventRequest\x12\x1b\n" +
	"\tegress_id\x18\x01 \x01(\tR\begressId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12#\n" +
	"\rlifetime_days\x18\x05 \x01(\x03R\flifetimeDays\"\x1c\n" +
	"\x1aGstPipelineDebugDotRequest\"8\n" +
	"\x1bGstPipelineDebugDotResponse\x12\x19\n" +
	"\bdot_file\x18\x01 \x01(\tR\adotFile\"a\n" +
	"\fPProfRequest\x12!\n" +
	"\fprofile_name\x18\x01 \x01(\tR\vprofileName\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\x12\x14\n" +
	"\x05debug\x18\x03 \x01(\x05R\x05debug\".\n" +
	"\rPProfResponse\x12\x1d\n" +
	"\n" +
	"pprof_file\x18\x01 \x01(\fR\tpprofFile\"\x10\n" +
	"\x0eMetricsRequest\"+\n" +
	"\x0fMetricsResponse\x12\x18\n" +
	"\ametrics\x18\x01 \x01(\tR\ametrics\")\n" +
	"\x11KillEgressRequest\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xe5\x02\n" +
	"\rEgressService\x12B\n" +
	"\fHandlerReady\x12\x18.ipc.HandlerReadyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12>\n" +
	"\rHandlerUpdate\x12\x13.livekit.EgressInfo\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\x0fHandlerFinished\x12\x1b.ipc.HandlerFinishedRequest\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\vReplayReady\x12\x17.rpc.EgressReadyRequest\x1a\x18.rpc.EgressReadyResponse\"\x00\x12B\n" +
	"\fStorageEvent\x12\x18.ipc.StorageEventRequest\x1a\x16.google.protobuf.Empty\"\x002\x96\x02\n" +
	"\rEgressHandler\x12U\n" +
	"\x0eGetPipelineDot\x12\x1f.ipc.GstPipelineDebugDotRequest\x1a .ipc.GstPipelineDebugDotResponse\"\x00\x123\n" +
	"\bGetPProf\x12\x11.ipc.PProfRequest\x1a\x12.ipc.PProfResponse\"\x00\x129\n" +
	"\n" +
	"GetMetrics\x12\x13.ipc.MetricsRequest\x1a\x14.ipc.MetricsResponse\"\x00\x12>\n" +
	"\n" +
	"KillEgress\x12\x16.ipc.KillEgressRequest\x1a\x16.google.protobuf.Empty\"\x00B#Z!github.com/livekit/egress/pkg/ipcb\x06proto3"

var (
	file_ipc_proto_rawDescOnce sync.Once
	file_ipc_proto_rawDescData []byte
)

func file_ipc_proto_rawDescGZIP() []byte {
	file_ipc_proto_rawDescOnce.Do(func() {
		file_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ipc_proto_rawDesc), len(file_ipc_proto_rawDesc)))
	})
	return file_ipc_proto_rawDescData
}

var file_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ipc_proto_goTypes = []any{
	(*HandlerReadyRequest)(nil),         // 0: ipc.HandlerReadyRequest
	(*HandlerFinishedRequest)(nil),      // 1: ipc.HandlerFinishedRequest
	(*StorageEventRequest)(nil),         // 2: ipc.StorageEventRequest
	(*GstPipelineDebugDotRequest)(nil),  // 3: ipc.GstPipelineDebugDotRequest
	(*GstPipelineDebugDotResponse)(nil), // 4: ipc.GstPipelineDebugDotResponse
	(*PProfRequest)(nil),                // 5: ipc.PProfRequest
	(*PProfResponse)(nil),               // 6: ipc.PProfResponse
	(*MetricsRequest)(nil),              // 7: ipc.MetricsRequest
	(*MetricsResponse)(nil),             // 8: ipc.MetricsResponse
	(*KillEgressRequest)(nil),           // 9: ipc.KillEgressRequest
	(*livekit.EgressInfo)(nil),          // 10: livekit.EgressInfo
	(*rpc.EgressReadyRequest)(nil),      // 11: rpc.EgressReadyRequest
	(*emptypb.Empty)(nil),               // 12: google.protobuf.Empty
	(*rpc.EgressReadyResponse)(nil),     // 13: rpc.EgressReadyResponse
}
var file_ipc_proto_depIdxs = []int32{
	10, // 0: ipc.HandlerFinishedRequest.info:type_name -> livekit.EgressInfo
	0,  // 1: ipc.EgressService.HandlerReady:input_type -> ipc.HandlerReadyRequest
	10, // 2: ipc.EgressService.HandlerUpdate:input_type -> livekit.EgressInfo
	1,  // 3: ipc.EgressService.HandlerFinished:input_type -> ipc.HandlerFinishedRequest
	11, // 4: ipc.EgressService.ReplayReady:input_type -> rpc.EgressReadyRequest
	2,  // 5: ipc.EgressService.StorageEvent:input_type -> ipc.StorageEventRequest
	3,  // 6: ipc.EgressHandler.GetPipelineDot:input_type -> ipc.GstPipelineDebugDotRequest
	5,  // 7: ipc.EgressHandler.GetPProf:input_type -> ipc.PProfRequest
	7,  // 8: ipc.EgressHandler.GetMetrics:input_type -> ipc.MetricsRequest
	9,  // 9: ipc.EgressHandler.KillEgress:input_type -> ipc.KillEgressRequest
	12, // 10: ipc.EgressService.HandlerReady:output_type -> google.protobuf.Empty
	12, // 11: ipc.EgressService.HandlerUpdate:output_type -> google.protobuf.Empty
	12, // 12: ipc.EgressService.HandlerFinished:output_type -> google.protobuf.Empty
	13, // 13: ipc.EgressService.ReplayReady:output_type -> rpc.EgressReadyResponse
	12, // 14: ipc.EgressService.StorageEvent:output_type -> google.protobuf.Empty
	4,  // 15: ipc.EgressHandler.GetPipelineDot:output_type -> ipc.GstPipelineDebugDotResponse
	6,  // 16: ipc.EgressHandler.GetPProf:output_type -> ipc.PProfResponse
	8,  // 17: ipc.EgressHandler.GetMetrics:output_type -> ipc.MetricsResponse
	12, // 18: ipc.EgressHandler.KillEgress:output_type -> google.protobuf.Empty
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_ipc_proto_init() }
func file_ipc_proto_init() {
	if File_ipc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ipc_proto_rawDesc), len(file_ipc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ipc_proto_goTypes,
		DependencyIndexes: file_ipc_proto_depIdxs,
		MessageInfos:      file_ipc_proto_msgTypes,
	}.Build()
	File_ipc_proto = out.File
	file_ipc_proto_goTypes = nil
	file_ipc_proto_depIdxs = nil
}
