// Copyright 2026 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"text/template"
)

var dimVarName = map[string]string{
	"RequestType":    "RequestTypes",
	"PublisherCodec": "PublisherCodecs",
	"OutputType":     "OutputTypes",
	"OutputEncoding": "OutputEncodings",
}

var generatedTemplate = template.Must(template.New("generated").Parse(`// Copyright 2026 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build integration

// Code generated by cmd/generate-tests. DO NOT EDIT.

package test

var generatedTests = []*testCase{
{{- range .Tests}}
	{
		// Covers: {{.Covers}}
		name: "{{.Name}}",
		options: []Mutation{
{{- range .Options}}
			{{.}},
{{- end}}
		},
	},
{{- end}}
}
`))

type templateTest struct {
	Name    string
	Covers  string
	Options []string
}

func repoRoot() string {
	_, filename, _, _ := runtime.Caller(0)
	// filename is cmd/generate-tests/main.go, walk up three levels
	return filepath.Dir(filepath.Dir(filepath.Dir(filename)))
}

func main() {
	validate := flag.Bool("validate", false, "validate that generated file is up to date")
	flag.Parse()

	tests := Cover(allDimensions)

	fmt.Print(CoverageReport(tests))

	// Build template data.
	var data struct {
		Tests []templateTest
	}
	for _, t := range tests {
		// Build covers comment: Dimension.Name for each value, sorted.
		covers := make([]string, len(t.Values))
		for i, v := range t.Values {
			covers[i] = v.Dimension + "." + v.Name
		}
		sort.Strings(covers)

		// Build option lines: VarName.ValueName.Apply
		options := make([]string, len(t.Values))
		for i, v := range t.Values {
			varName := dimVarName[v.Dimension]
			options[i] = varName + "." + v.Name + ".Apply"
		}
		// Sort options for deterministic output.
		sort.Strings(options)

		data.Tests = append(data.Tests, templateTest{
			Name:    t.Name,
			Covers:  strings.Join(covers, ", "),
			Options: options,
		})
	}

	var buf bytes.Buffer
	if err := generatedTemplate.Execute(&buf, data); err != nil {
		fmt.Fprintf(os.Stderr, "template error: %v\n", err)
		os.Exit(1)
	}

	outputFile := filepath.Join(repoRoot(), "test", "generated_tests.go")

	if *validate {
		existing, err := os.ReadFile(outputFile)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error reading %s: %v\nRun `mage GenerateTests` to generate it.\n", outputFile, err)
			os.Exit(1)
		}
		if !bytes.Equal(existing, buf.Bytes()) {
			fmt.Fprintf(os.Stderr, "generated_tests.go is out of date. Run `mage GenerateTests` to update.\n")
			os.Exit(1)
		}
		fmt.Println("generated_tests.go is up to date.")
		return
	}

	if err := os.WriteFile(outputFile, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outputFile, err)
		os.Exit(1)
	}

	// Run gofmt on the output file.
	cmd := exec.Command("gofmt", "-w", outputFile)
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "gofmt error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("\nWrote %s\n", outputFile)
}
