// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"context"
	"os/exec"
	"sync"

	"github.com/livekit/egress/pkg/ipc"
	"github.com/livekit/egress/pkg/service"
	"github.com/livekit/protocol/livekit"
	"github.com/livekit/protocol/rpc"
	"github.com/prometheus/client_golang/prometheus"
)

type FakeProcessManager struct {
	AbortProcessStub        func(string, error)
	abortProcessMutex       sync.RWMutex
	abortProcessArgsForCall []struct {
		arg1 string
		arg2 error
	}
	AlreadyExistsStub        func(string) bool
	alreadyExistsMutex       sync.RWMutex
	alreadyExistsArgsForCall []struct {
		arg1 string
	}
	alreadyExistsReturns struct {
		result1 bool
	}
	alreadyExistsReturnsOnCall map[int]struct {
		result1 bool
	}
	GetActiveEgressIDsStub        func() []string
	getActiveEgressIDsMutex       sync.RWMutex
	getActiveEgressIDsArgsForCall []struct {
	}
	getActiveEgressIDsReturns struct {
		result1 []string
	}
	getActiveEgressIDsReturnsOnCall map[int]struct {
		result1 []string
	}
	GetContextStub        func(string) context.Context
	getContextMutex       sync.RWMutex
	getContextArgsForCall []struct {
		arg1 string
	}
	getContextReturns struct {
		result1 context.Context
	}
	getContextReturnsOnCall map[int]struct {
		result1 context.Context
	}
	GetGRPCClientStub        func(string) (ipc.EgressHandlerClient, error)
	getGRPCClientMutex       sync.RWMutex
	getGRPCClientArgsForCall []struct {
		arg1 string
	}
	getGRPCClientReturns struct {
		result1 ipc.EgressHandlerClient
		result2 error
	}
	getGRPCClientReturnsOnCall map[int]struct {
		result1 ipc.EgressHandlerClient
		result2 error
	}
	GetGatherersStub        func() []prometheus.Gatherer
	getGatherersMutex       sync.RWMutex
	getGatherersArgsForCall []struct {
	}
	getGatherersReturns struct {
		result1 []prometheus.Gatherer
	}
	getGatherersReturnsOnCall map[int]struct {
		result1 []prometheus.Gatherer
	}
	GetStatusStub        func(map[string]interface{})
	getStatusMutex       sync.RWMutex
	getStatusArgsForCall []struct {
		arg1 map[string]interface{}
	}
	HandlerStartedStub        func(string) error
	handlerStartedMutex       sync.RWMutex
	handlerStartedArgsForCall []struct {
		arg1 string
	}
	handlerStartedReturns struct {
		result1 error
	}
	handlerStartedReturnsOnCall map[int]struct {
		result1 error
	}
	KillAllStub        func()
	killAllMutex       sync.RWMutex
	killAllArgsForCall []struct {
	}
	KillProcessStub        func(string, error)
	killProcessMutex       sync.RWMutex
	killProcessArgsForCall []struct {
		arg1 string
		arg2 error
	}
	LaunchStub        func(context.Context, string, *rpc.StartEgressRequest, *livekit.EgressInfo, *exec.Cmd) error
	launchMutex       sync.RWMutex
	launchArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 *rpc.StartEgressRequest
		arg4 *livekit.EgressInfo
		arg5 *exec.Cmd
	}
	launchReturns struct {
		result1 error
	}
	launchReturnsOnCall map[int]struct {
		result1 error
	}
	ProcessFinishedStub        func(string)
	processFinishedMutex       sync.RWMutex
	processFinishedArgsForCall []struct {
		arg1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProcessManager) AbortProcess(arg1 string, arg2 error) {
	fake.abortProcessMutex.Lock()
	fake.abortProcessArgsForCall = append(fake.abortProcessArgsForCall, struct {
		arg1 string
		arg2 error
	}{arg1, arg2})
	stub := fake.AbortProcessStub
	fake.recordInvocation("AbortProcess", []interface{}{arg1, arg2})
	fake.abortProcessMutex.Unlock()
	if stub != nil {
		fake.AbortProcessStub(arg1, arg2)
	}
}

func (fake *FakeProcessManager) AbortProcessCallCount() int {
	fake.abortProcessMutex.RLock()
	defer fake.abortProcessMutex.RUnlock()
	return len(fake.abortProcessArgsForCall)
}

func (fake *FakeProcessManager) AbortProcessCalls(stub func(string, error)) {
	fake.abortProcessMutex.Lock()
	defer fake.abortProcessMutex.Unlock()
	fake.AbortProcessStub = stub
}

func (fake *FakeProcessManager) AbortProcessArgsForCall(i int) (string, error) {
	fake.abortProcessMutex.RLock()
	defer fake.abortProcessMutex.RUnlock()
	argsForCall := fake.abortProcessArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProcessManager) AlreadyExists(arg1 string) bool {
	fake.alreadyExistsMutex.Lock()
	ret, specificReturn := fake.alreadyExistsReturnsOnCall[len(fake.alreadyExistsArgsForCall)]
	fake.alreadyExistsArgsForCall = append(fake.alreadyExistsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.AlreadyExistsStub
	fakeReturns := fake.alreadyExistsReturns
	fake.recordInvocation("AlreadyExists", []interface{}{arg1})
	fake.alreadyExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProcessManager) AlreadyExistsCallCount() int {
	fake.alreadyExistsMutex.RLock()
	defer fake.alreadyExistsMutex.RUnlock()
	return len(fake.alreadyExistsArgsForCall)
}

func (fake *FakeProcessManager) AlreadyExistsCalls(stub func(string) bool) {
	fake.alreadyExistsMutex.Lock()
	defer fake.alreadyExistsMutex.Unlock()
	fake.AlreadyExistsStub = stub
}

func (fake *FakeProcessManager) AlreadyExistsArgsForCall(i int) string {
	fake.alreadyExistsMutex.RLock()
	defer fake.alreadyExistsMutex.RUnlock()
	argsForCall := fake.alreadyExistsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeProcessManager) AlreadyExistsReturns(result1 bool) {
	fake.alreadyExistsMutex.Lock()
	defer fake.alreadyExistsMutex.Unlock()
	fake.AlreadyExistsStub = nil
	fake.alreadyExistsReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeProcessManager) AlreadyExistsReturnsOnCall(i int, result1 bool) {
	fake.alreadyExistsMutex.Lock()
	defer fake.alreadyExistsMutex.Unlock()
	fake.AlreadyExistsStub = nil
	if fake.alreadyExistsReturnsOnCall == nil {
		fake.alreadyExistsReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.alreadyExistsReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeProcessManager) GetActiveEgressIDs() []string {
	fake.getActiveEgressIDsMutex.Lock()
	ret, specificReturn := fake.getActiveEgressIDsReturnsOnCall[len(fake.getActiveEgressIDsArgsForCall)]
	fake.getActiveEgressIDsArgsForCall = append(fake.getActiveEgressIDsArgsForCall, struct {
	}{})
	stub := fake.GetActiveEgressIDsStub
	fakeReturns := fake.getActiveEgressIDsReturns
	fake.recordInvocation("GetActiveEgressIDs", []interface{}{})
	fake.getActiveEgressIDsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProcessManager) GetActiveEgressIDsCallCount() int {
	fake.getActiveEgressIDsMutex.RLock()
	defer fake.getActiveEgressIDsMutex.RUnlock()
	return len(fake.getActiveEgressIDsArgsForCall)
}

func (fake *FakeProcessManager) GetActiveEgressIDsCalls(stub func() []string) {
	fake.getActiveEgressIDsMutex.Lock()
	defer fake.getActiveEgressIDsMutex.Unlock()
	fake.GetActiveEgressIDsStub = stub
}

func (fake *FakeProcessManager) GetActiveEgressIDsReturns(result1 []string) {
	fake.getActiveEgressIDsMutex.Lock()
	defer fake.getActiveEgressIDsMutex.Unlock()
	fake.GetActiveEgressIDsStub = nil
	fake.getActiveEgressIDsReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeProcessManager) GetActiveEgressIDsReturnsOnCall(i int, result1 []string) {
	fake.getActiveEgressIDsMutex.Lock()
	defer fake.getActiveEgressIDsMutex.Unlock()
	fake.GetActiveEgressIDsStub = nil
	if fake.getActiveEgressIDsReturnsOnCall == nil {
		fake.getActiveEgressIDsReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.getActiveEgressIDsReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeProcessManager) GetContext(arg1 string) context.Context {
	fake.getContextMutex.Lock()
	ret, specificReturn := fake.getContextReturnsOnCall[len(fake.getContextArgsForCall)]
	fake.getContextArgsForCall = append(fake.getContextArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetContextStub
	fakeReturns := fake.getContextReturns
	fake.recordInvocation("GetContext", []interface{}{arg1})
	fake.getContextMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProcessManager) GetContextCallCount() int {
	fake.getContextMutex.RLock()
	defer fake.getContextMutex.RUnlock()
	return len(fake.getContextArgsForCall)
}

func (fake *FakeProcessManager) GetContextCalls(stub func(string) context.Context) {
	fake.getContextMutex.Lock()
	defer fake.getContextMutex.Unlock()
	fake.GetContextStub = stub
}

func (fake *FakeProcessManager) GetContextArgsForCall(i int) string {
	fake.getContextMutex.RLock()
	defer fake.getContextMutex.RUnlock()
	argsForCall := fake.getContextArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeProcessManager) GetContextReturns(result1 context.Context) {
	fake.getContextMutex.Lock()
	defer fake.getContextMutex.Unlock()
	fake.GetContextStub = nil
	fake.getContextReturns = struct {
		result1 context.Context
	}{result1}
}

func (fake *FakeProcessManager) GetContextReturnsOnCall(i int, result1 context.Context) {
	fake.getContextMutex.Lock()
	defer fake.getContextMutex.Unlock()
	fake.GetContextStub = nil
	if fake.getContextReturnsOnCall == nil {
		fake.getContextReturnsOnCall = make(map[int]struct {
			result1 context.Context
		})
	}
	fake.getContextReturnsOnCall[i] = struct {
		result1 context.Context
	}{result1}
}

func (fake *FakeProcessManager) GetGRPCClient(arg1 string) (ipc.EgressHandlerClient, error) {
	fake.getGRPCClientMutex.Lock()
	ret, specificReturn := fake.getGRPCClientReturnsOnCall[len(fake.getGRPCClientArgsForCall)]
	fake.getGRPCClientArgsForCall = append(fake.getGRPCClientArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetGRPCClientStub
	fakeReturns := fake.getGRPCClientReturns
	fake.recordInvocation("GetGRPCClient", []interface{}{arg1})
	fake.getGRPCClientMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProcessManager) GetGRPCClientCallCount() int {
	fake.getGRPCClientMutex.RLock()
	defer fake.getGRPCClientMutex.RUnlock()
	return len(fake.getGRPCClientArgsForCall)
}

func (fake *FakeProcessManager) GetGRPCClientCalls(stub func(string) (ipc.EgressHandlerClient, error)) {
	fake.getGRPCClientMutex.Lock()
	defer fake.getGRPCClientMutex.Unlock()
	fake.GetGRPCClientStub = stub
}

func (fake *FakeProcessManager) GetGRPCClientArgsForCall(i int) string {
	fake.getGRPCClientMutex.RLock()
	defer fake.getGRPCClientMutex.RUnlock()
	argsForCall := fake.getGRPCClientArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeProcessManager) GetGRPCClientReturns(result1 ipc.EgressHandlerClient, result2 error) {
	fake.getGRPCClientMutex.Lock()
	defer fake.getGRPCClientMutex.Unlock()
	fake.GetGRPCClientStub = nil
	fake.getGRPCClientReturns = struct {
		result1 ipc.EgressHandlerClient
		result2 error
	}{result1, result2}
}

func (fake *FakeProcessManager) GetGRPCClientReturnsOnCall(i int, result1 ipc.EgressHandlerClient, result2 error) {
	fake.getGRPCClientMutex.Lock()
	defer fake.getGRPCClientMutex.Unlock()
	fake.GetGRPCClientStub = nil
	if fake.getGRPCClientReturnsOnCall == nil {
		fake.getGRPCClientReturnsOnCall = make(map[int]struct {
			result1 ipc.EgressHandlerClient
			result2 error
		})
	}
	fake.getGRPCClientReturnsOnCall[i] = struct {
		result1 ipc.EgressHandlerClient
		result2 error
	}{result1, result2}
}

func (fake *FakeProcessManager) GetGatherers() []prometheus.Gatherer {
	fake.getGatherersMutex.Lock()
	ret, specificReturn := fake.getGatherersReturnsOnCall[len(fake.getGatherersArgsForCall)]
	fake.getGatherersArgsForCall = append(fake.getGatherersArgsForCall, struct {
	}{})
	stub := fake.GetGatherersStub
	fakeReturns := fake.getGatherersReturns
	fake.recordInvocation("GetGatherers", []interface{}{})
	fake.getGatherersMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProcessManager) GetGatherersCallCount() int {
	fake.getGatherersMutex.RLock()
	defer fake.getGatherersMutex.RUnlock()
	return len(fake.getGatherersArgsForCall)
}

func (fake *FakeProcessManager) GetGatherersCalls(stub func() []prometheus.Gatherer) {
	fake.getGatherersMutex.Lock()
	defer fake.getGatherersMutex.Unlock()
	fake.GetGatherersStub = stub
}

func (fake *FakeProcessManager) GetGatherersReturns(result1 []prometheus.Gatherer) {
	fake.getGatherersMutex.Lock()
	defer fake.getGatherersMutex.Unlock()
	fake.GetGatherersStub = nil
	fake.getGatherersReturns = struct {
		result1 []prometheus.Gatherer
	}{result1}
}

func (fake *FakeProcessManager) GetGatherersReturnsOnCall(i int, result1 []prometheus.Gatherer) {
	fake.getGatherersMutex.Lock()
	defer fake.getGatherersMutex.Unlock()
	fake.GetGatherersStub = nil
	if fake.getGatherersReturnsOnCall == nil {
		fake.getGatherersReturnsOnCall = make(map[int]struct {
			result1 []prometheus.Gatherer
		})
	}
	fake.getGatherersReturnsOnCall[i] = struct {
		result1 []prometheus.Gatherer
	}{result1}
}

func (fake *FakeProcessManager) GetStatus(arg1 map[string]interface{}) {
	fake.getStatusMutex.Lock()
	fake.getStatusArgsForCall = append(fake.getStatusArgsForCall, struct {
		arg1 map[string]interface{}
	}{arg1})
	stub := fake.GetStatusStub
	fake.recordInvocation("GetStatus", []interface{}{arg1})
	fake.getStatusMutex.Unlock()
	if stub != nil {
		fake.GetStatusStub(arg1)
	}
}

func (fake *FakeProcessManager) GetStatusCallCount() int {
	fake.getStatusMutex.RLock()
	defer fake.getStatusMutex.RUnlock()
	return len(fake.getStatusArgsForCall)
}

func (fake *FakeProcessManager) GetStatusCalls(stub func(map[string]interface{})) {
	fake.getStatusMutex.Lock()
	defer fake.getStatusMutex.Unlock()
	fake.GetStatusStub = stub
}

func (fake *FakeProcessManager) GetStatusArgsForCall(i int) map[string]interface{} {
	fake.getStatusMutex.RLock()
	defer fake.getStatusMutex.RUnlock()
	argsForCall := fake.getStatusArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeProcessManager) HandlerStarted(arg1 string) error {
	fake.handlerStartedMutex.Lock()
	ret, specificReturn := fake.handlerStartedReturnsOnCall[len(fake.handlerStartedArgsForCall)]
	fake.handlerStartedArgsForCall = append(fake.handlerStartedArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.HandlerStartedStub
	fakeReturns := fake.handlerStartedReturns
	fake.recordInvocation("HandlerStarted", []interface{}{arg1})
	fake.handlerStartedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProcessManager) HandlerStartedCallCount() int {
	fake.handlerStartedMutex.RLock()
	defer fake.handlerStartedMutex.RUnlock()
	return len(fake.handlerStartedArgsForCall)
}

func (fake *FakeProcessManager) HandlerStartedCalls(stub func(string) error) {
	fake.handlerStartedMutex.Lock()
	defer fake.handlerStartedMutex.Unlock()
	fake.HandlerStartedStub = stub
}

func (fake *FakeProcessManager) HandlerStartedArgsForCall(i int) string {
	fake.handlerStartedMutex.RLock()
	defer fake.handlerStartedMutex.RUnlock()
	argsForCall := fake.handlerStartedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeProcessManager) HandlerStartedReturns(result1 error) {
	fake.handlerStartedMutex.Lock()
	defer fake.handlerStartedMutex.Unlock()
	fake.HandlerStartedStub = nil
	fake.handlerStartedReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProcessManager) HandlerStartedReturnsOnCall(i int, result1 error) {
	fake.handlerStartedMutex.Lock()
	defer fake.handlerStartedMutex.Unlock()
	fake.HandlerStartedStub = nil
	if fake.handlerStartedReturnsOnCall == nil {
		fake.handlerStartedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.handlerStartedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProcessManager) KillAll() {
	fake.killAllMutex.Lock()
	fake.killAllArgsForCall = append(fake.killAllArgsForCall, struct {
	}{})
	stub := fake.KillAllStub
	fake.recordInvocation("KillAll", []interface{}{})
	fake.killAllMutex.Unlock()
	if stub != nil {
		fake.KillAllStub()
	}
}

func (fake *FakeProcessManager) KillAllCallCount() int {
	fake.killAllMutex.RLock()
	defer fake.killAllMutex.RUnlock()
	return len(fake.killAllArgsForCall)
}

func (fake *FakeProcessManager) KillAllCalls(stub func()) {
	fake.killAllMutex.Lock()
	defer fake.killAllMutex.Unlock()
	fake.KillAllStub = stub
}

func (fake *FakeProcessManager) KillProcess(arg1 string, arg2 error) {
	fake.killProcessMutex.Lock()
	fake.killProcessArgsForCall = append(fake.killProcessArgsForCall, struct {
		arg1 string
		arg2 error
	}{arg1, arg2})
	stub := fake.KillProcessStub
	fake.recordInvocation("KillProcess", []interface{}{arg1, arg2})
	fake.killProcessMutex.Unlock()
	if stub != nil {
		fake.KillProcessStub(arg1, arg2)
	}
}

func (fake *FakeProcessManager) KillProcessCallCount() int {
	fake.killProcessMutex.RLock()
	defer fake.killProcessMutex.RUnlock()
	return len(fake.killProcessArgsForCall)
}

func (fake *FakeProcessManager) KillProcessCalls(stub func(string, error)) {
	fake.killProcessMutex.Lock()
	defer fake.killProcessMutex.Unlock()
	fake.KillProcessStub = stub
}

func (fake *FakeProcessManager) KillProcessArgsForCall(i int) (string, error) {
	fake.killProcessMutex.RLock()
	defer fake.killProcessMutex.RUnlock()
	argsForCall := fake.killProcessArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProcessManager) Launch(arg1 context.Context, arg2 string, arg3 *rpc.StartEgressRequest, arg4 *livekit.EgressInfo, arg5 *exec.Cmd) error {
	fake.launchMutex.Lock()
	ret, specificReturn := fake.launchReturnsOnCall[len(fake.launchArgsForCall)]
	fake.launchArgsForCall = append(fake.launchArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 *rpc.StartEgressRequest
		arg4 *livekit.EgressInfo
		arg5 *exec.Cmd
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.LaunchStub
	fakeReturns := fake.launchReturns
	fake.recordInvocation("Launch", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.launchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProcessManager) LaunchCallCount() int {
	fake.launchMutex.RLock()
	defer fake.launchMutex.RUnlock()
	return len(fake.launchArgsForCall)
}

func (fake *FakeProcessManager) LaunchCalls(stub func(context.Context, string, *rpc.StartEgressRequest, *livekit.EgressInfo, *exec.Cmd) error) {
	fake.launchMutex.Lock()
	defer fake.launchMutex.Unlock()
	fake.LaunchStub = stub
}

func (fake *FakeProcessManager) LaunchArgsForCall(i int) (context.Context, string, *rpc.StartEgressRequest, *livekit.EgressInfo, *exec.Cmd) {
	fake.launchMutex.RLock()
	defer fake.launchMutex.RUnlock()
	argsForCall := fake.launchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeProcessManager) LaunchReturns(result1 error) {
	fake.launchMutex.Lock()
	defer fake.launchMutex.Unlock()
	fake.LaunchStub = nil
	fake.launchReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProcessManager) LaunchReturnsOnCall(i int, result1 error) {
	fake.launchMutex.Lock()
	defer fake.launchMutex.Unlock()
	fake.LaunchStub = nil
	if fake.launchReturnsOnCall == nil {
		fake.launchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.launchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProcessManager) ProcessFinished(arg1 string) {
	fake.processFinishedMutex.Lock()
	fake.processFinishedArgsForCall = append(fake.processFinishedArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ProcessFinishedStub
	fake.recordInvocation("ProcessFinished", []interface{}{arg1})
	fake.processFinishedMutex.Unlock()
	if stub != nil {
		fake.ProcessFinishedStub(arg1)
	}
}

func (fake *FakeProcessManager) ProcessFinishedCallCount() int {
	fake.processFinishedMutex.RLock()
	defer fake.processFinishedMutex.RUnlock()
	return len(fake.processFinishedArgsForCall)
}

func (fake *FakeProcessManager) ProcessFinishedCalls(stub func(string)) {
	fake.processFinishedMutex.Lock()
	defer fake.processFinishedMutex.Unlock()
	fake.ProcessFinishedStub = stub
}

func (fake *FakeProcessManager) ProcessFinishedArgsForCall(i int) string {
	fake.processFinishedMutex.RLock()
	defer fake.processFinishedMutex.RUnlock()
	argsForCall := fake.processFinishedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeProcessManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProcessManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.ProcessManager = new(FakeProcessManager)
