name: Template Test
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - build/template/Dockerfile
      - template-default/**
      - template-sdk/**

defaults:
  run:
    working-directory: template-default

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build
